spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demoapp_delivery
    username: postgres
    password: Nut@n803212
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: true
      retry:
        enabled: false
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
        multiplier: 1.1
  config:
    import: optional:classpath:optional.properties
  kafka:
    consumer:
      group-id: delivery-service-group

server:
  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration
app:
  jwt:
    secret: ZGVtb0FwcFNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw
    expiration: 86400000

# Service-specific configurations
delivery:
  status:
    pending: PENDING
    processing: PROCESSING
    shipped: SHIPPED
    delivered: DELIVERED
    cancelled: CANCELLED
  delivery:
    tracking:
      update-interval: 30 # seconds
    assignment:
      max-radius: 5000 # meters
      max-active-orders: 3
  maps:
    api-key: ${MAPS_API_KEY:defaultMapKey}
    distance-matrix-url: https://maps.googleapis.com/maps/api/distancematrix/json
    geocoding-url: https://maps.googleapis.com/maps/api/geocode/json 