server:
  port: 8081

spring:
  application:
    name: authentication-service

  # Optional: fetch overrides from your Config Server
  # Uncomment if you have a Config Server running
  # config:
  #   import: optional:configserver:http://localhost:8889

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demoapp_auth}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Nut@n803212}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: ${JWT_EXPIRATION:86400000}        # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days

mfa:
  issuer: ${MFA_ISSUER:DemoApp}
  length: ${MFA_CODE_LENGTH:6}
  validity: ${MFA_CODE_VALIDITY:300}           # 5 minutes

security:
  max-failed-attempts: ${MAX_FAILED_ATTEMPTS:5}
  lock-duration: ${ACCOUNT_LOCK_DURATION:300}   # 5 minutes
  password:
    min-length: ${PASSWORD_MIN_LENGTH:8}
    require-special: ${PASSWORD_REQUIRE_SPECIAL:true}
    require-numbers: ${PASSWORD_REQUIRE_NUMBERS:true}
    require-uppercase: ${PASSWORD_REQUIRE_UPPERCASE:true}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
