spring:
  application:
    name: discovery-service
  # Import config from config server (optional)
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true 