spring:
  application:
    name: subscription-service
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1500
        max-attempts: 10000
        max-interval: 1000
  datasource:
    url: jdbc:postgresql://localhost:5432/demoapp_subscription
    username: postgres
    password: Nut@n803212
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:8763
    consumer:
      group-id: subscription-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8778
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      subscriptionService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  retry:
    instances:
      subscriptionService:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      subscriptionService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    root: INFO
    com.demoApp.subscription: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

jwt:
  secret: ZGVtb0FwcFNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

subscription:
  pagination:
    default-page-size: 20
    max-page-size: 100
  kafka:
    topics:
      subscription-events: subscription-events
      payment-updates: payment-updates
  plans:
    renewal-reminder-days: 7
    grace-period-days: 3
  payment:
    currency: INR
    retry-attempts: 3
    retry-delay: 1h

notification:
  service:
    url: http://localhost:8085

payment:
  service:
    url: http://localhost:8086
