CREATE TABLE IF NOT EXISTS deliveries (
    id BIGSERIAL PRIMARY KEY,
    tracking_code VARCHAR(255) UNIQUE,
    order_reference_id BIGINT NOT NULL,
    order_reference_type VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    mess_id BIGINT NOT NULL,
    delivery_person_id BIGINT,
    delivery_address TEXT NOT NULL,
    delivery_city VARCHAR(100),
    delivery_state VARCHAR(100),
    delivery_postal_code VARCHAR(20),
    delivery_instructions TEXT,
    contact_name VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    pickup_latitude DOUBLE PRECISION,
    pickup_longitude DOUBLE PRECISION,
    delivery_latitude DOUBLE PRECISION,
    delivery_longitude DOUBLE PRECISION,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    scheduled_pickup_time TIMESTAMP,
    scheduled_delivery_time TIMESTAMP,
    actual_pickup_time TIMESTAMP,
    actual_delivery_time TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    rating INTEGER,
    feedback TEXT,
    issue_description TEXT,
    resolution TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    cancelled_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delivery_persons (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    vehicle_number VARCHAR(50),
    vehicle_type VARCHAR(50),
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    is_active BOOLEAN DEFAULT true,
    average_rating DOUBLE PRECISION,
    total_ratings INTEGER,
    mess_id BIGINT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_type VARCHAR(50),
    id_number VARCHAR(100),
    id_proof_url TEXT,
    profile_image_url TEXT,
    id_proof_image_url TEXT,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    last_latitude DOUBLE PRECISION,
    last_longitude DOUBLE PRECISION,
    last_location_update_time TIMESTAMP
); 