package com.demoApp.subscription.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class PaymentResponse {
    private boolean success;
    private String paymentId;
    private String errorMessage;

    // Constructor, getters, and setters are generated by Lombok (@Data and @Builder)
}
