server:
  port: 8783
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/demoapp_payment
    username: postgres
    password: Nut@n803212
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.demoApp.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        batch-size: 16384
        buffer-memory: 33554432
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
      chain:
        strategy:
          content:
            enabled: true
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1500
        max-attempts: 10000
        max-interval: 3000
    discovery:
      enabled: true

# Discovery client (rename as needed if not using Eureka)
discovery:
  url: http://discovery:8761/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 20
        maxWaitDuration: 0s

stripe:
  apiKey: ${STRIPE_API_KEY:sk_test_...}
  publicKey: ${STRIPE_PUBLISHABLE_KEY:pk_test_...}
  secretKey: ${STRIPE_SECRET_KEY:sk_test_...}

payment:
  apiKey: ${PAYMENT_GATEWAY_API_KEY:test_key}
  secret: ${PAYMENT_GATEWAY_SECRET:test_secret}
  gateway:
    url: https://payment.demoapp.com
    timeout: 30000
  retry:
    max-attempts: 3
    backoff: 1000

app:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKey}
    expiration: ${JWT_EXPIRATION:86400000}
  security:
    encryption:
      key: ${ENCRYPTION_KEY:defaultEncryptionKey}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      max-age: 3600
  transaction:
    expiry: 900 # 15 minutes in seconds

logging:
  level:
    com.demoApp.payment: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

