package com.demoApp.order.entity;

public enum NotificationType {
    ORDER_CONFIRMED,
    ORDER_PREPARING,
    ORDER_READY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    DELIVERY_ASSIGNED,
    DELIVERY_STARTED,
    DELIVERY_COMPLETED,
    DELIVERY_FAILED,
    SYSTEM_ALERT,
    ORDER_STATUS,
    ORDER_UPDATE
} 